### ISSUE TITLE
Classification results should be formatted such that they can be used by the Emotion Synthesis group

### ISSUE THREAD

**Issue by diegocasmo** [diegocasmo/iis-project#15]
- [x] Create format for Emotion Synthesis group (must include accuracy and confidence)
  - [x] Update ``final-solution.ipynb`` notebook to include confusion matrix/accuracy
- [x] Send email to Emotion Synthesis group with format and a documentation of it
- [x] Classify a couple of examples and send them to the Emotion Synthesis (in the same email from above)

**Comment by ankurshukla03** [comment]
```json
{
	"ANGER": 60,
	"HAPPY": 5,
	"SURPRISE": 15, 
	"FEAR": 10,
	"SADNESS": 5,
	"DISGUST": 5
}
```

**Comment by tristaaan** [comment]
The only thing we need to change to meet this format is --at least for the MLP classifier-- we need to have 6 output neurons. 

I don't know how to do this for KNN and others...
