### ISSUE TITLE
Record a video showing a demo of the system developed during the project

### ISSUE THREAD

**Issue by diegocasmo** [diegocasmo/iis-project#16]
- [x] Record a video showing a demo of the system developed during the project

**Comment by tristaaan** [comment]
There are some good Chrome Extensions for doing this, I'd link one but the one I usually use is not available anymore I guess.

**Comment by tristaaan** [comment]
This is done, where should the video live?

**Comment by diegocasmo** [comment]
I was thinking maybe we could add at the begging of the report a list with a link to the repo and the video?

**Comment by ankurshukla03** [comment]
yeah that sounds reasonable.

**Comment by tristaaan** [comment]
https://drive.google.com/open?id=1StqS9HfuPTlCiSpTLgUq-d6VgnfLkSdv

-Tristan Wright

**Comment by tristaaan** [comment]
** https://youtu.be/Owlukfpjqqk
