### ISSUE TITLE
Report - Additional Requirements

### ISSUE THREAD

**Issue by diegocasmo** [diegocasmo/iis-project#28]
In addition to the tasks mentioned in the report's skeleton, the following must be covered: 
- The report should include, at the beginning:
  - [x] a summary of the work and main results
  - [x] what has worked and what has not
  - [ ] role played by each individual group member
  - [x] one paragraph explaining the contribution of each individual student should be included
- Others (mandatory as well):
  - [x] Your original project specifications as an Appendix (the Appendix does not count towards the 5-page limit)

**Comment by tristaaan** [comment]
pulling out role to separate issue
